### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by AlexErrant** [Azarattum/CRStore#1]
Hi! Would you mind giving this repo a license? I'd love to copy https://github.com/Azarattum/CRStore/blob/main/src/lib/database/dialect.ts for [my own proj](https://github.com/AlexErrant/Pentive). Thanks!

**Comment by Azarattum** [comment]
Honestly speaking I really don't care about licenses... So, I've never taken a time to compare and choose one. Maybe I should just slap MIT on it, since it seems like what everyone's using. Would that work for you @AlexErrant?

**Comment by AlexErrant** [comment]
Yeah... I definitely had my eyes glaze over when trying to compare licenses. https://choosealicense.com/ is a good starting point, if you wanna look around. If not, MIT works well for me - thanks!

**Comment by Azarattum** [comment]
Btw, is there a way to add a license without a `LICENSE` file, so that it can be recognized by NPM, GitHub, etc? Maybe like a link in readme of something. I really don't like the idea of a copy pasted bulk of text just sitting there in the project root.

**Comment by AlexErrant** [comment]
NPM packages can define a license in their `packge.json` as described [here](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#license). For example:

```json
{
  "name": "solid-start-monorepo",
  "description": "Official starter for SolidJS",
  "version": "0.1.0",
  "author": "Ryan Carniato",
  "type": "module",
  "license": "MIT"
}
```

But, unfortunately, I believe that having a `LICENSE` in the project root is the standard. I'm not sure if having a `"license": "MIT"` in the `package.json` has any legal standing, or if it's just there for the bots. My impression is that it's for the bots, since the somewhat minimal "`MIT`" doesn't give lawyers any handholds on which to create problems for themselves. I've given up on having a clean root dir myself 😭

**Comment by Azarattum** [comment]
Completed with https://github.com/Azarattum/CRStore/commit/3a5b8c853d3e7864fe88cc6fd264a3a1bb3e566a
