### ISSUE TITLE
Question about migrations

### ISSUE THREAD

**Issue by cotyhamilton** [Azarattum/CRStore#3]
I'm using cr-sqlite in a static SvelteKit project and stumbled upon this library and it looks nicer than running raw sql and handling async stores myself.

If my primary (only) data lives in the browser with a named sqlite db, what happens when I update the schema? My original plan with my method is to write migrations manually and apply them on each first page load, wondering if this library can handle this case.

**Comment by Azarattum** [comment]
The library doesn’t handle migration currently. That might be implemented later, though. For it to work properly there need to be a clear path defined by cr-sqlite itself. I might be wrong, but I think migrations are still an open question for cr-sqlite in general.

As for now, you can implement any migration logic required by your app yourself. You can run any Kysely or even raw SQL query in an `update` function.

```ts
import { database, sql } from "crstore";

const { update } = database(schema);

update((db) => db.insertInto("todos").values({ ... }).execute());
update((db) => sql`INSERT INTO todos …`.execute(db));
```

**Comment by cotyhamilton** [comment]
Perfect, thanks!
